version: '3.3'


services:
  nginx:
    image: nginx:latest
    hostname: nginx
    env_file:
      - .env.dev
    ports:
      - 80:80
    volumes:
      - /home/ubuntu/git_clone/dating_service/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/ssl/certs/dating_service-selfsigned.crt:/etc/ssl/certs/dating_service-selfsigned.crt
      - /etc/ssl/private/dating_service-selfsigned.key:/etc/ssl/private/dating_service-selfsigned.key
    networks:
      - common_network
    depends_on:
      - telegram_bot

  cache:
    image: redis:latest
    hostname: cache
    env_file:
      - .env.dev
    ports:
      - 6379:6379
    networks:
      - common_network
      
  db:
    image: postgres:13
    hostname: db
    env_file:
      - .env.dev
    ports:
      - 5432:5432
    networks:
      - common_network

  llm_service:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile_llm
    image: llm_service
    hostname: llm_service
    # command: tail -F anything
    entrypoint: ./entrypoint-llm-service.sh
    env_file:
      - .env.dev
    volumes:
      - /home/ubuntu/hugging_face_cache:/root/.cache/huggingface
    ports:
      - 4321:4321
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - common_network

  telegram_bot:
    build:
        context: .
        dockerfile: ./deploy/Dockerfile_tg
    image: telegram_bot
    hostname: telegram_bot
    # command: tail -F anything
    entrypoint: ./entrypoint-tg-service.sh
    env_file:
      - .env.dev
    ports:
      - 8000:8000
    depends_on:
      - db
      - llm_service
    tty: true
    networks:
      - common_network


networks:
  common_network:
    driver: bridge
